config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  resources :trips, only: [:index, :show] do
    resources :notes, only: [:index, :destroy, :create], defaults: { format: :json }
    resources :flights, only: [:index, :destroy, :create], defaults: { format: :json }
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  # Very simple authorization for the app. Add more for other models later.
  # See specs at "spec/lib/ability_spec.rb"
  def initialize(user)
    if user.present?
      can :manage, Trip do |trip|
        trip.accessible_by?(user)
      end

      can :manage, Note do |note|
        note.trip.accessible_by?(user)
      end
    else
      can :read, Trip, privacy: Trip::PRIVACY_TYPES[:PUBLIC]

      can :read, Note do |note|
        note.trip.public?
      end
    end
  end
end

app/models/financial_record.rb
class FinancialRecord < ActiveRecord::Base
  belongs_to :trip
  validates_presence_of :trip, :user_id, :creator_id, :description

end

app/models/flight.rb
class Flight < ActiveRecord::Base
  validates :flight_number, :creator_id, :trip_id, :description, :arrival_date, presence: true

  belongs_to :user, foreign_key: :creator_id
  belongs_to :trip
end

app/models/lodging.rb
class Lodging < ActiveRecord::Base
  validates :start_date, :name, :end_date, :trip_id, presence: true

  belongs_to :trip
  belongs_to :user, foreign_key: :creator_id
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :trip
  belongs_to :user, foreign_key: :creator_id
end

app/models/shopping_list.rb
class ShoppingList < ActiveRecord::Base
  validates :description, :trip_id, :creator_id, presence: true

  belongs_to :trip
  belongs_to :user, foreign_key: :creator_id
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  PRIVACY_TYPES = {
    PUBLIC: 1,
    PRIVATE: 2
  }

  belongs_to :creator, class_name: "User"
  has_many :financial_records
  has_many :user_trips
  has_many :notes
  has_many :flights
  has_many :users, through: :user_trips

  validates :name, presence: true
  validates :privacy, inclusion: { in: PRIVACY_TYPES.values }
  validate :ensure_start_date_earlier_than_end_date
  validates_presence_of :creator

  def public?
    self.privacy == PRIVACY_TYPES[:PUBLIC]
  end

  def accessible_by?(user)
    self.users.include?(user)
  end

  private

  def ensure_start_date_earlier_than_end_date
    errors.add(:start_date, "Start date must come before the end date") unless (self.start_date < self.end_date)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: {message: "Email address cannot be blank." },
            format: { with: VALID_EMAIL_REGEX, message: "Email address is not valid."},
            uniqueness: {case_sensitive: false, message: "Email address already exist."}

  has_many :user_trips
  has_many :trips, through: :user_trips
end

app/models/user_trip.rb
class UserTrip < ActiveRecord::Base
  belongs_to :user
  belongs_to :trip
  validates :user_id, presence: true
  validates :trip_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :filter_devise_permitted_params, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def filter_devise_permitted_params
    registration_params = [:name, :email, :password, :password_confirmation]
    devise_parameter_sanitizer.for(:sign_up) {
        |u| u.permit(registration_params)
    }
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path()
  end

  def after_sign_in_path_for(resource_or_scope)
    trips_path()
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_filter :load_trip

  def index
    @flights = @trip.flights
  end

  def create
    params[:arrival_date] = Date.strptime(params[:arrival_date], '%m/%d/%Y')
    @flight = @trip.flights.create(permitted_params.merge({creator_id: current_user.id}))
  end

  def destroy

  end

  private

  def load_trip
    @trip = Trip.find(params[:trip_id])
  end

  def permitted_params
    params.permit(:flight_number, :arrival_date, :description)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  rescue_from CanCan::AccessDenied do |exception|  # TODO: turn this into a shared module
    respond_to do |format|
      format.json { render :json => 'Access Denied', status: 403 }
    end
  end

  load_and_authorize_resource :trip

  def index
    @notes = @trip.notes
  end

  def create
    @note = @trip.notes.create(permitted_params.merge({creator_id: current_user.id}))
  end

  def destroy

  end

  private

  def permitted_params
    params.permit(:description)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = current_user.trips
  end

  def show
    @trip = Trip.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.slim
.main-header
  - if current_user
    heading--large= "You are logged in as #{current_user.name}"
    = link_to "Sign Out", destroy_user_session_path(), method: :delete
  - else
    heading--large You are not logged in. Please log in to update the board
    = link_to "Sign In", new_user_session_path()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tripplanner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: "layouts/header" %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/trips/index.html.slim
.trip-index
  p List of your trips
  ul
  - @trips.each do |trip|
    li
      = link_to trip.name, trip_path(trip), target: "_blank"
  end

app/views/trips/show.html.slim
div
  .trip-info-container[data={ id: @trip.id }]
    .trip-info-inner
      .heading--titan= @trip.name
      br
      .heading--medium= @trip.start_date.strftime("Start date: %m/%d/%Y")
      .heading--medium= @trip.end_date.strftime("End date: %m/%d/%Y")
      br
      .heading--medium Participants:
      .heading--small #{@trip.users.collect(&:name).join(", ")}

  .other-info-container ng-app="commonApp"
    .notes-container.flex-column ng-controller="NotesCtrl"
      .heading--medium.text-emphasized Notes
      .heading--small Suggestions of what to do / other info
      div.flex-column-inner
        .notes-item ng-class="{ 'even' : $index % 2}" ng-repeat="note in notes"
          | {{ note.description }}
          br
          | - {{ note.creator_name }}
      - if current_user
        .heading--medium.text-emphasized Submit new notes
        div.flex-column-edit
          textarea ng-model="description"
          a href="#" ng-click="submitForm($event)" Submit

    .flights-container.flex-column ng-controller="FlightsCtrl"
      .heading--medium.text-emphasized Fights
      .heading--small Add your flights here. Specify infos in the description field.
      div.flex-column-inner
        .notes-item ng-class="{ 'even' : $index % 2}" ng-repeat="flight in flights"
          b
            | {{ flight.flight_number }}
          | : {{ flight.description }}
          | - {{ flight.arrival_date }}
          br
          | - {{ flight.creator_name }}
      - if current_user
        .heading--medium.text-emphasized Add more flights
        div.flex-column-edit
          | Flight number:
          input type="text" ng-model="flight_info.flight_number"
          br
          | Description:
          input type="text" ng-model="flight_info.description"
          br
          | Arrival Date (mm/dd/yyyy):
          input type="text" ng-model="flight_info.arrival_date"
          br
          a href="#" ng-click="submitForm($event)" Submit

    .lodging-container.flex-column ng-controller="LodgingCtrl"
      .heading--medium.text-emphasized Lodging (currently uses dummy data)
      .heading--small Add a list of all places you will be staying.
      div.flex-column-inner
        .notes-item ng-class="{ 'even' : $index % 2}" ng-repeat="lodging in lodgings"
          b
            | {{ lodging.start_date }} - {{ lodging.end_date }}
          | : {{ lodging.name }}
          br
          | - {{ lodging.creator_name }}

    .finance-tracking-container.flex-column ng-controller="FinanceCtrl"
      .heading--medium.text-emphasized Finance (currently uses dummy data)
      .heading--small Keep track of spending /credits for each person.
      div.flex-column-inner
        .notes-item ng-class="{ 'even' : $index % 2}" ng-repeat="record in finances"
          b
            | $ {{ record.amount }}
          | : {{ record.description }}
          br
          | Paid by {{ record.creditor }}
          br
          | Debtors: {{ record.debtors }}